### ISSUE TITLE
Changing the enviorment variable value 0 to 1 

### ISSUE THREAD

**Issue by jarulss1** [payu-intrepos/Android-SDK-Sample-App#10]
I have issue when i changing the enviorment variable value 0 to 1 

only Verify API button only shown. Other buttons are hidden. 

Thanks for advance

![screenshot_2015-08-26-11-28-15-867](https://cloud.githubusercontent.com/assets/7993236/9494976/a7aafe14-4c26-11e5-99f9-1544168140b0.jpeg)

**Comment by saravanan72** [comment]
I am having same issue while using the keys which was provided by payumoney account... i have merchant key, merchant id and salt key.... even though, it says like this..
