### ISSUE TITLE
App crashes on Clicking on BankList Spinner of Netbanking.

### ISSUE THREAD

**Issue by pavitramirraw** [payu-intrepos/Android-SDK-Sample-App#13]
Sdk
versionCode 3
versionName '2.4'

I am using customized UI for netbanking. It crashes when I click on 'Bank List Spinner of Netbanking' after updating to following library version.

(Crashes after updating to below version)
compile 'com.android.support:appcompat-v7:23.0.1'
compile 'com.android.support:design:23.0.1'

(Works correctly on below version)
compile 'com.android.support:appcompat-v7:22.2.0'
compile 'com.android.support:design:22.2.1'

Find the Git Repository over here.
https://github.com/pavitramirraw/PayuCrashOnBankListClick

You can find the demo video below.
https://youtu.be/l34E11xxNcU

LOGCAT:
10-14 17:18:16.745 21484-21484/com.payu.payutestapp D/mali_winsys: new_window_surface returns 0x3000
10-14 17:18:16.750 21484-21484/com.payu.payutestapp D/ProgressBar: updateDrawableBounds: left = 0
10-14 17:18:16.750 21484-21484/com.payu.payutestapp D/ProgressBar: updateDrawableBounds: top = 0
10-14 17:18:16.750 21484-21484/com.payu.payutestapp D/ProgressBar: updateDrawableBounds: right = 96
10-14 17:18:16.750 21484-21484/com.payu.payutestapp D/ProgressBar: updateDrawableBounds: bottom = 96
10-14 17:18:16.895 21484-7346/com.payu.payutestapp D/dalvikvm: GC_FOR_ALLOC freed 1705K, 20% free 11578K/14328K, paused 35ms, total 35ms
10-14 17:18:16.905 21484-21493/com.payu.payutestapp I/System.out: FinalizerDaemon calls detatch()
10-14 17:18:17.035 21484-7346/com.payu.payutestapp I/System.out: AsyncTask #2 calls detatch()
10-14 17:18:17.110 21484-21484/com.payu.payutestapp E/ViewRootImpl: sendUserActionEvent() mView == null
10-14 17:18:17.260 21484-21484/com.payu.payutestapp D/mali_winsys: new_window_surface returns 0x3000
10-14 17:18:18.410 21484-21484/com.payu.payutestapp I/dalvikvm: Could not find method android.widget.Spinner.getPopupContext, referenced from method android.support.v7.widget.AppCompatSpinner.getPopupContext
10-14 17:18:18.410 21484-21484/com.payu.payutestapp W/dalvikvm: VFY: unable to resolve virtual method 16296: Landroid/widget/Spinner;.getPopupContext ()Landroid/content/Context;
10-14 17:18:18.410 21484-21484/com.payu.payutestapp D/dalvikvm: VFY: replacing opcode 0x6f at 0x000b
10-14 17:18:18.410 21484-21484/com.payu.payutestapp I/dalvikvm: Could not find method android.content.Context.getDrawable, referenced from method android.support.v7.widget.AppCompatSpinner.setPopupBackgroundResource
10-14 17:18:18.410 21484-21484/com.payu.payutestapp W/dalvikvm: VFY: unable to resolve virtual method 284: Landroid/content/Context;.getDrawable (I)Landroid/graphics/drawable/Drawable;
10-14 17:18:18.410 21484-21484/com.payu.payutestapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0004
10-14 17:18:18.485 21484-21484/com.payu.payutestapp D/mali_winsys: new_window_surface returns 0x3000
10-14 17:18:18.955 21484-7385/com.payu.payutestapp I/System.out: AsyncTask #3 calls detatch()
10-14 17:18:18.985 21484-21484/com.payu.payutestapp E/dalvikvm: Could not find class 'android.widget.ThemedSpinnerAdapter', referenced from method android.support.v7.widget.AppCompatSpinner$DropDownAdapter.<init>
10-14 17:18:18.985 21484-21484/com.payu.payutestapp W/dalvikvm: VFY: unable to resolve instanceof 1950 (Landroid/widget/ThemedSpinnerAdapter;) in Landroid/support/v7/widget/AppCompatSpinner$DropDownAdapter;
10-14 17:18:18.985 21484-21484/com.payu.payutestapp D/dalvikvm: VFY: replacing opcode 0x20 at 0x0016
10-14 17:18:19.685 21484-7400/com.payu.payutestapp I/System.out: AsyncTask #4 calls detatch()
10-14 17:18:20.410 21484-21484/com.payu.payutestapp W/dalvikvm: method Landroid/support/v7/internal/widget/ListViewCompat;.lookForSelectablePosition incorrectly overrides package-private method with same name in Landroid/widget/ListView;
10-14 17:18:20.435 21484-21484/com.payu.payutestapp D/AbsListView: Get MotionRecognitionManager
10-14 17:18:20.460 21484-21484/com.payu.payutestapp D/AndroidRuntime: Shutting down VM
10-14 17:18:20.460 21484-21484/com.payu.payutestapp W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4181cc08)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime: FATAL EXCEPTION: main
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime: Process: com.payu.payutestapp, PID: 21484
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime: java.lang.NullPointerException
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at android.widget.TextView.checkForRelayout(TextView.java:8220)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at android.widget.TextView.setText(TextView.java:4989)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at android.widget.TextView.setText(TextView.java:4788)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at android.widget.TextView.setText(TextView.java:4763)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at com.payu.sdk.adapters.NetBankingAdapter.getView(NetBankingAdapter.java:62)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at android.widget.BaseAdapter.getDropDownView(BaseAdapter.java:71)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at android.support.v7.widget.AppCompatSpinner$DropDownAdapter.getDropDownView(AppCompatSpinner.java:624)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at android.support.v7.widget.AppCompatSpinner$DropDownAdapter.getView(AppCompatSpinner.java:620)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at android.support.v7.internal.widget.ListViewCompat.measureHeightOfChildrenCompat(ListViewCompat.java:290)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at android.support.v7.widget.ListPopupWindow.buildDropDown(ListPopupWindow.java:1200)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at android.support.v7.widget.ListPopupWindow.show(ListPopupWindow.java:584)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at android.support.v7.widget.AppCompatSpinner$DropdownPopup.show(AppCompatSpinner.java:766)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at android.support.v7.widget.AppCompatSpinner.performClick(AppCompatSpinner.java:424)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:19311)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:146)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5692)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
10-14 17:18:20.470 21484-21484/com.payu.payutestapp E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

**Comment by pandeeswaran** [comment]
Spinner is not working

**Comment by pandeeswaran** [comment]
No action performed when clicking on bank info spinner
