### ISSUE TITLE
<!DOCTYPE of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by balasasidhar** [payu-intrepos/Android-SDK-Sample-App#21]
I'm getting following error while using my test/production account's merchant key & salt. 
<!DOCTYPE of type java.lang.String cannot be converted to JSONObject

It is working if I'm using Merchant Key & Salt from Sample App

**Comment by santoshrokhade** [comment]
This error is coming for targetSdkVersion 25, but working fine for targetSdkVersion 23

**Comment by PRAKHAR1997** [comment]
I'm getting the same issue while integrating but test app in running fine? why is it soo??

**Comment by ajesh-n** [comment]
I'm also getting the same issue when setting production environment but in staging env app is running fine?
 W/System.err: org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
 W/System.err:     at org.json.JSON.typeMismatch(JSON.java:111)
 W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:160)
 W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:173)
 W/System.err:     at com.payu.india.Tasks.ValueAddedServiceTask.doInBackground(ValueAddedServiceTask.java:105)
 W/System.err:     at com.payu.india.Tasks.ValueAddedServiceTask.doInBackground(ValueAddedServiceTask.java:52)
 W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by Narensanju** [comment]
i am also getting the same error..response 5014 returning.

**Comment by ajesh-n** [comment]
It works only for PayU ( https://payubiz.in ) not with PayUMoney ( https://www.payumoney.com ).
You can't use payU money merchant id and key with this sdk.
I found that currently payU  ( https://www.payumoney.com ) money only provides PnP ( com.payumoney.sdkui:plug-n-play:1.0.0 ) option.

**Comment by Narensanju** [comment]
thanx for the info

**Comment by harshitaahuja** [comment]
Getting error 
`org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
01-11 21:35:57.461 23919-26097/com.savitroday.savischools W/System.err:     at org.json.JSON.typeMismatch(JSON.java:111)
01-11 21:35:57.461 23919-26097/com.savitroday.savischools W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:160)
01-11 21:35:57.461 23919-26097/com.savitroday.savischools W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:173)
01-11 21:35:57.461 23919-26097/com.savitroday.savischools W/System.err:     at com.payu.india.Tasks.ValueAddedServiceTask.doInBackground(ValueAddedServiceTask.java:105)
01-11 21:35:57.461 23919-26097/com.savitroday.savischools W/System.err:     at com.payu.india.Tasks.ValueAddedServiceTask.doInBackground(ValueAddedServiceTask.java:52)
01-11 21:35:57.461 23919-26097/com.savitroday.savischools W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:304)
01-11 21:35:57.461 23919-26097/com.savitroday.savischools W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-11 21:35:57.461 23919-26097/com.savitroday.savischools W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
01-11 21:35:57.461 23919-26097/com.savitroday.savischools W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-11 21:35:57.461 23919-26097/com.savitroday.savischools W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-11 21:35:57.461 23919-26097/com.savitroday.savischools W/System.err:     at java.lang.Thread.run(Thread.java:761)
`

Any solutions.. Please help me with this

**Comment by JacobSamro** [comment]
Same issue :(

**Comment by kevintorch** [comment]
Same here... <!DOCTYPE of type java.lang.String cannot be converted to JSONObject on Production Environment...

**Comment by ajayka** [comment]
Same issue
