### ISSUE TITLE
Payment successful but no updation in my PaYU account

### ISSUE THREAD

**Issue by ankush-134** [payu-intrepos/Android-SDK-Sample-App#22]
I am using this code for integrating payment gateway in my app,with my merchant key,and salt as well. but the problem is that payment is completed successfully ,balance also deducted from my account but  there is no notification aur balance updation in my PaYU account .

**Comment by gauravgaria** [comment]
Hi, have you successfully integrated with payu gateway.?

**Comment by UdayasankarT** [comment]
yeah, but can't find to whom the money has been sent
