### ISSUE TITLE
How to generate hash for setPaymentRelatedDetailsForMobileSdkHash() method? 

### ISSUE THREAD

**Issue by arjunkn** [payu-intrepos/Android-SDK-Sample-App#25]
How to generate hash for setPaymentRelatedDetailsForMobileSdkHash() method? Only Payment hash generation method is documented. When i submit with only payment hash set it shows "mandatory param hash is missing".

**Comment by partha4u21** [comment]
https://payumobile.gitbook.io/sdk-integration/hash-generation
