### ISSUE TITLE
payumoney Integration with mobile application 

### ISSUE THREAD

**Issue by preetisanger** [payu-intrepos/Android-SDK-Sample-App#33]
i have some issue
how to use this link:=" https://test.payumoney.com/payment/op/calculateHashForTest"

**Comment by vipin04** [comment]
Hi Preeti,

Merchants are not supposed to use this link in their production app. The above link calculates hash for test merchant key. For live apps, hash must be calculated with the merchants own salt (a kind of secret password), on their own server. The above link will work as-is on provided sample app, if test environment is selected. You can check how it has been used in InitialViewController file of sample app.

But it should never be used in your live app.

**Comment by asudhakar** [comment]
any demo for this?

**Comment by asudhakar** [comment]
i need for server end

**Comment by preetisanger** [comment]
which type demo ?????

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by asudhakar** [comment]
fixed that thanks for the reply 


   <?php

$key=$_POST["key"];

$salt="xxxxxxxx";
$txnId=$_POST["txnid"];
$amount=$_POST["amount"];
$productName=$_POST["productInfo"];
$firstName=$_POST["firstName"];
$email=$_POST["email"];
$udf1=$_POST["udf1"];
$udf2=$_POST["udf2"];
$udf3=$_POST["udf3"];
$udf4=$_POST["udf4"];
$udf5=$_POST["udf5"];

$payhash_str = $key . '|' . checkNull($txnId) . '|' .checkNull($amount)  . '|' .checkNull($productName)  . '|' . checkNull($firstName) . '|' . checkNull($email) . '|' . checkNull($udf1) . '|' . checkNull($udf2) . '|' . checkNull($udf3) . '|' . checkNull($udf4) . '|' . checkNull($udf5) . '|' . $salt;


function checkNull($value) {
            if ($value == null) {
                  return '';
            } else {
                  return $value;
            }
      }


$hash = strtolower(hash('sha512', $payhash_str));
$arr['result'] = $hash;
$arr['status']=0;
$arr['errorCode']=null;
$arr['responseCode']=null;
$arr['hashtest']=$payhash_str;
$output=$arr;


echo json_encode($output);

?>

**Comment by asudhakar** [comment]
```
   <?php

$key=$_POST["key"];

$salt="xxxxxxx";
$txnId=$_POST["txnid"];
$amount=$_POST["amount"];
$productName=$_POST["productInfo"];
$firstName=$_POST["firstName"];
$email=$_POST["email"];
$udf1=$_POST["udf1"];
$udf2=$_POST["udf2"];
$udf3=$_POST["udf3"];
$udf4=$_POST["udf4"];
$udf5=$_POST["udf5"];

$payhash_str = $key . '|' . checkNull($txnId) . '|' .checkNull($amount)  . '|' .checkNull($productName)  . '|' . checkNull($firstName) . '|' . checkNull($email) . '|' . checkNull($udf1) . '|' . checkNull($udf2) . '|' . checkNull($udf3) . '|' . checkNull($udf4) . '|' . checkNull($udf5) . '|' . $salt;


function checkNull($value) {
            if ($value == null) {
                  return '';
            } else {
                  return $value;
            }
      }


$hash = strtolower(hash('sha512', $payhash_str));
$arr['result'] = $hash;
$arr['status']=0;
$arr['errorCode']=null;
$arr['responseCode']=null;
$arr['hashtest']=$payhash_str;
$output=$arr;


echo json_encode($output);

?>
```

**Comment by PradeepSheoran** [comment]
https://drive.google.com/open?id=102H4xkEXty_WTbuXfC4L5wAxJe08qe0D
