### ISSUE TITLE
How to generate Hash Key for Production Environment

### ISSUE THREAD

**Issue by KomalAseum** [payu-intrepos/Android-SDK-Sample-App#37]
I have Integrate PayUMoney in my android app using SDK, It is working good in Test Environment but it is not working on Production Environment, In Test Environment there is URL for get Hash Keys . URL: https://payu.herokuapp.com/get_hash but For Production(Live) I have no idea about how to generate Hash Key? It should generate from own android side or server side through the Api, Kindly guide me.

**Comment by trinadhkoya** [comment]
have same problem here?

**Comment by archanasoni1** [comment]
same problem?

**Comment by maheshlantech** [comment]
Generate hash key on your server
https://github.com/payu-intrepos/Documentations/wiki/4.-Server-Side
