### ISSUE TITLE
Payumoney sdk integration in android app (org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject)

### ISSUE THREAD

**Issue by Tejas513** [payu-intrepos/Android-SDK-Sample-App#44]
Please help me with the Error, it's getting the same error with the client-side hash generation and server-side hash generation, below is the error code of the logcat.

org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
04-13 09:16:19.847 5140-5265/hackers.com.payumoneydemo W/System.err:     at org.json.JSON.typeMismatch(JSON.java:111)
04-13 09:16:19.847 5140-5265/hackers.com.payumoneydemo W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:160)
04-13 09:16:19.847 5140-5265/hackers.com.payumoneydemo W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:173)
04-13 09:16:19.847 5140-5265/hackers.com.payumoneydemo W/System.err:     at com.payu.india.Tasks.ValueAddedServiceTask.doInBackground(ValueAddedServiceTask.java:105)
04-13 09:16:19.847 5140-5265/hackers.com.payumoneydemo W/System.err:     at com.payu.india.Tasks.ValueAddedServiceTask.doInBackground(ValueAddedServiceTask.java:52)
04-13 09:16:19.847 5140-5265/hackers.com.payumoneydemo W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
04-13 09:16:19.847 5140-5265/hackers.com.payumoneydemo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-13 09:16:19.847 5140-5265/hackers.com.payumoneydemo W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
04-13 09:16:19.848 5140-5265/hackers.com.payumoneydemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-13 09:16:19.848 5140-5265/hackers.com.payumoneydemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-13 09:16:19.848 5140-5265/hackers.com.payumoneydemo W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by Tejas513** [comment]
We are waiting for your valuable replay. 

Thank you

**Comment by himgupta229** [comment]
Please file your issues at https://github.com/payu-intrepos/payumoney-new-sample-app/issues or reach out at techsupport@payumoney.com.
