### ISSUE TITLE
Regarding getting invalid merchant key and salt with client account

### ISSUE THREAD

**Issue by ravkothari** [payu-intrepos/Android-SDK-Sample-App#46]
Hi Sir/Madam,
    I am getting problem to implement PayUMoney in android side.
    I am getting error while i pass the merchant key and salt that show incorrect merchant key and salt with 
    with use of client account merchant key and salt.
     please help me out as soon as possible. 

     I am waiting for your positive response. 
     Thanks

**Comment by himgupta229** [comment]
Please drop a mail on techsupport@payumoney.com to get a better support
