### ISSUE TITLE
Affect Google RECEIVE_SMS privacy policy to pay u sdk?

### ISSUE THREAD

**Issue by DarshanPatel23** [payu-intrepos/Android-SDK-Sample-App#49]
I have got mail from google for remove unnecessary RECEIVE_SMS permission from the project, but only in sdkui library manifest, got this permission.

**Comment by himgupta229** [comment]
Please fill the permission [form](https://docs.google.com/forms/d/e/1FAIpQLSfCnRaa4b1VuHhE4gVekWJc_V0Zt4XiTlsKsTipTlPg5ECA7Q/viewform) for raising an exception of financial transactions.
We are working on fixing the same, will be releasing sdk soon.

**Comment by himgupta229** [comment]
Hi Everyone, you can remove RECEIVE_SMS permission from the sdkui module and update the Custom Browser to 7.3.0 version. We have added support for SMS Retriever client in version 7.3.0 and removed RECEIVE_SMS permission.

**Comment by niranjanskashyap** [comment]
Hi, @himgupta229 We are using the PayU SDK in our app and faced the similar issue mentioned above. I have removed the RECEIVE_SMS permission from the sdkui module manifest file and update Custom Browser to 7.3.0 but still i able to see the RECEIVE_SMS permission in permission list. We are not using RECEIVE_SMS permission anywhere else. Please assist on this issue.

**Comment by himgupta229** [comment]
> Hi, @himgupta229 We are using the PayU SDK in our app and faced the similar issue mentioned above. I have removed the RECEIVE_SMS permission from the sdkui module manifest file and update Custom Browser to 7.3.0 but still i able to see the RECEIVE_SMS permission in permission list. We are not using RECEIVE_SMS permission anywhere else. Please assist on this issue.

Hi,

Can you please check with below code snippet .
<uses-permission android:name="android.permission.RECEIVE_SMS" tools:node="remove"/>
<uses-permission android:name="android.permission.READ_SMS" tools:node="remove"/>
<uses-permission android:name="android.permission.SEND_SMS" tools:node="remove"/>

**Comment by niranjanskashyap** [comment]
Hi,

Thanks for the response. The above given code snippet solves the SMS related permission issue.

**Comment by sushantchaturvedi1895** [comment]
Hi @himgupta229 , I added compile 'com.payu.india:payu-sdk:4.4.1'
    compile 'com.payu.custombrowser:payu-custom-browser:7.3.0' these dependency but after sync I am getting these error  

com/unify/notification/MyFirebaseInstanceIDService.java	
error: cannot access zzb
class file for com.google.firebase.iid.zzb not found	
error: cannot find symbol variable this	
error: package this does not exist

pleases tell me solution because only 3 days left in 9th march date given by google 



com/unify/notification/MyFirebaseInstanceIDService.java |  
-- | --
error: cannot access zzb class file for com.google.firebase.iid.zzb not found |  
error: cannot find symbol variable this |  
error: package this does not exist |

**Comment by himgupta229** [comment]
> Hi @himgupta229 , I added compile 'com.payu.india:payu-sdk:4.4.1'
> compile 'com.payu.custombrowser:payu-custom-browser:7.3.0' these dependency but after sync I am getting these error
> 
> com/unify/notification/MyFirebaseInstanceIDService.java
> error: cannot access zzb
> class file for com.google.firebase.iid.zzb not found
> error: cannot find symbol variable this
> error: package this does not exist
> 
> pleases tell me solution because only 3 days left in 9th march date given by google
> 
> com/unify/notification/MyFirebaseInstanceIDService.java	 
> error: cannot access zzb class file for com.google.firebase.iid.zzb not found	 
> error: cannot find symbol variable this	 
> error: package this does not exist

This might be an issue with mismatch dependency of the Play-service version.We are using below dependencies:
`'com.android.support:appcompat-v7:27.1.0'
'com.android.support:customtabs:27.1.0'
'com.android.support:support-compat:27.1.0'
'com.android.support:recyclerview-v7:27.1.0'
'com.google.android.gms:play-services-auth-api-phone:16.0.0'`

**Comment by sushantchaturvedi1895** [comment]
**this is sdk level gradle**

apply plugin: 'com.android.library'

android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 2
        versionName "2.0.1"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.payu.india:payu-sdk:4.4.1'

    compile 'com.payu.custombrowser:payu-custom-browser:7.3.0'
    compile 'com.android.support:support-v4:27.1.0'

    compile 'com.android.support:appcompat-v7:27.1.0'
    compile 'com.android.support:customtabs:27.1.0'
    compile 'com.android.support:support-compat:27.1.0'
    compile 'com.android.support:recyclerview-v7:27.1.0'
    compile 'com.google.android.gms:play-services-auth-api-phone:16.0.0'
}


**and this is app level gradle file**

 implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
    //    implementation 'org.lucasr.twowayview:twowayview:0.1.4'
    implementation 'com.android.support:appcompat-v7:27.0.2'
    implementation 'com.android.support:design:27.0.2'
    implementation 'com.android.support:recyclerview-v7:27.0.2'
    implementation 'com.android.support:cardview-v7:27.0.2'
    implementation 'com.android.support:multidex:1.0.1'
    implementation 'com.dk.animation.circle:library:0.1.0@aar'
    implementation 'cz.msebera.android:httpclient:4.4.1.1'
    implementation 'com.android.volley:volley:1.1.0'
    implementation 'com.google.firebase:firebase-messaging:11.2.2'
    implementation 'com.google.firebase:firebase-appindexing:11.2.2'
    implementation 'com.squareup.retrofit2:retrofit:2.0.2'
    implementation 'com.squareup.retrofit2:converter-gson:2.0.2'
    implementation 'org.jsoup:jsoup:1.10.1'
    //implementation 'com.facebook.android:facebook-android-sdk:[4,5)'
    implementation 'com.facebook.android:facebook-android-sdk:4.35.0'
    implementation 'com.google.android.gms:play-services-auth:11.2.2'
    implementation 'com.google.android.gms:play-services-analytics:11.2.2'
    implementation 'com.github.bumptech.glide:glide:3.5.2'
    //  implementation 'com.amplitude:android-sdk:2.14.1'
    implementation project(':sdkui')
    implementation 'com.amazonaws:aws-android-sdk-core:2.6.+'
    implementation 'com.amazonaws:aws-android-sdk-sns:2.6.+'
    implementation project(':map-sdk-production-release-19.2.2.8')
    implementation 'com.squareup.okhttp3:okhttp:3.10.0'
    implementation 'com.google.android.gms:play-services-gcm:11.2.2'
    implementation 'com.android.support:support-v4:27.0.2'
    implementation files('libs/activation.jar')
    implementation files('libs/additionnal.jar')
    implementation files('libs/mail.jar')
    implementation 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'


    compile('com.crashlytics.sdk.android:crashlytics:2.9.4@aar') {
        transitive = true;
    }
    compile "org.apache.httpcomponents:httpmime:4.2.3"
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    android {
        useLibrary 'org.apache.http.legacy'
    }

**Comment by sushantchaturvedi1895** [comment]
Hi @himgupta229 ,can u please tell me exact conflict in dependency or the process of migration from previous to 7.3.0

**Comment by himgupta229** [comment]
> Hi @himgupta229 ,can u please tell me exact conflict in dependency or the process of migration from previous to 7.3.0

You are using play-services version 11.2.2 whereas CustomBrowser is built upon 16.0.0 so either you can upgrade your existing play-services to 16.0.0 or exclude **"com.google.android.gms:play-services-auth-api-phone"** from CustomBrowser gradle

**Comment by sushantchaturvedi1895** [comment]
thank you @himgupta229 , It resolved...thanks for your support
