### ISSUE TITLE
Getting continuous slow Internet issue and finally ERR_CLEARTEXT_NOT_PERMITTED

### ISSUE THREAD

**Issue by ravitejaavv** [payu-intrepos/Android-SDK-Sample-App#51]
![screenshot_20190129-175620_20190129_180303578](https://user-images.githubusercontent.com/33521315/51908575-3c29b400-23f0-11e9-8fa3-1864d3c14e92.jpg)
![screenshot_20190129-175614_20190129_180303709](https://user-images.githubusercontent.com/33521315/51908576-3c29b400-23f0-11e9-8ab3-f251dc4b2f34.jpg)
![screenshot_20190129-175637_20190129_180303844](https://user-images.githubusercontent.com/33521315/51908577-3c29b400-23f0-11e9-9723-4f4de073d8ae.jpg)

Even-though i am using proper wifi connection getting above alert and finally error webpage.
Kindly provide me the solution for this

**Comment by Rahul-Hooda** [comment]
@ravitejaavv - Can you drop a mail to mobile.integration@payu.in with your merchant key for resolving this issue.

**Comment by ravitejaavv** [comment]
I have dropped a mail with details. Please do needful
Thanks

**Comment by himgupta229** [comment]
Cleartext urls(i.e. http) are not enabled by default to load in CustomBrowser for Security Concerns. Kindly change the url to https or enable cleartext traffic in your application manifest.
