### ISSUE TITLE
Re: PayUBaseActivity not found

### ISSUE THREAD

**Issue by max-pro** [payu-intrepos/Android-SDK-Sample-App#55]
Hello Team,

I'm trying to integrate payu SDK in-app. But it showing me error PayUBaseActivity not found. than I just copy paste sdkui folder from project. build get successful than after it showing error in sdkui folder fragmentManager not found, support not found.

**Comment by himgupta229** [comment]
Which release you are referring to?

**Comment by pandeyVishakha** [comment]
Hi Team,

I also have same issue, i just to integrate via gradle. I am using -
'com.payu.india:payu-sdk:4.4.8
but unable to find import for PayUBaseActivity 
How  i can launch payU UI?

**Comment by himgupta229** [comment]
> Hi Team,
> 
> I also have same issue, i just to integrate via gradle. I am using -
> 'com.payu.india:payu-sdk:4.4.8
> but unable to find import for PayUBaseActivity
> How i can launch payU UI?

PayUBaseActivity is present in **sdkui** module.Kindly import that module.

**Comment by pandeyVishakha** [comment]
Sure, but am not getting the purpose of using  this gradle
'com.payu.india:payu-sdk:4.4.8'
If i have to use the sdkUI module also.
Although all other files already available in sdkUI module, So, instead of using gradle, can i go with sdkUI only?
Am unable to schedule call with support team , If possible then provide me contact number for support team.

Thanks in advance!!

**Comment by himgupta229** [comment]
> Sure, but am not getting the purpose of using this gradle
> 'com.payu.india:payu-sdk:4.4.8'
> If i have to use the sdkUI module also.
> Although all other files already available in sdkUI module, So, instead of using gradle, can i go with sdkUI only?
> Am unable to schedule call with support team , If possible then provide me contact number for support team.
> 
> Thanks in advance!!

Hey,

Sdkui is kind of replacement of Merchant Checkout UI.It is for your reference only  in case you have your own checkout screen then you can use that.Gradle is of PayU PG sdk which sdkui consumes.So,if you are having your own Checkout you can refer the code of PaymentsActivity and PayUBaseActivity to how to invoke PG sdk and CB SDK(in case you are using).

**Comment by pandeyVishakha** [comment]
Ok Thanks @himgupta229
