### ISSUE TITLE
Unable to launch sdkUI in production environment

### ISSUE THREAD

**Issue by pandeyVishakha** [payu-intrepos/Android-SDK-Sample-App#56]
Hey Guys,

I just getting stucked with integrating sdkUI. Getting
 PPintent response check {"status":0,"msg":"Invalid Hash."} as response 

although unable to get details about getPaymentRelatedDetailsForMobileSdkHash()

Anyone help me out?

**Comment by himgupta229** [comment]
This error comes when hash is incorrectly calculated.

- Kindly check if you are not hitting staging env/hash calculation is correct.

- Remove below flags from AndroidManifest if present:

`

`

- For hash calculation, you can visit [here](https://github.com/payu-intrepos/Documentations/wiki/Server-Side#payment_related_details_for_mobile_sdk-api).

**Comment by himgupta229** [comment]
Closing as there is no update. Kindly reopen in case of any issue.
