### ISSUE TITLE
Hash mismatch in test payment & server side hash calculation guide?

### ISSUE THREAD

**Issue by akinfopark** [payu-intrepos/Android-SDK-Sample-App#60]
Downloaded the sample app. When I click pay now I get error as in video.
https://drive.google.com/file/d/1en-UlyT-BMPT1VduyXY6ZL5fn8tJWz-u/view?usp=sharing.
Where can I find Android side code for server side hash?

**Comment by himgupta229** [comment]
Kindly reach out to mobile.integration@payu.in
