### ISSUE TITLE
Updating the theme to material design

### ISSUE THREAD

**Issue by malhotramanik** [payu-intrepos/Android-SDK-Sample-App#62]
**Issue**
*After updating the theme to material design, options(Ok/Cancel) in the dialog for canceling payment are not visible.*

PR: Upgraded to latest versions #61
https://github.com/payu-intrepos/Android-SDK-Sample-App/pull/61#issue-499814836

![2020-10-08](https://user-images.githubusercontent.com/54097447/95448262-abef9080-0980-11eb-84a0-ed9a569079a7.jpg)

**Comment by shahbaz-payu** [comment]
Please override the style component below:
On styles.xml file
<style name="cb_dialog" parent="Theme.AppCompat.Light.Dialog.Alert">
    <item name="materialButtonStyle">@style/materialColor</item>
</style>
On styles.xml(v-22)
<style name="cb_dialog" parent="@android:style/Theme.DeviceDefault.Light.Dialog.Alert">
    <item name="materialButtonStyle">@style/materialColor</item>
</style>

**Comment by manujjagga421** [comment]
even after overriding style, i am not getting the desired result. i think this is becaus sdk is using appcompat.alertdialog instead of androidx.alertdialog.
