### ISSUE TITLE
payumoney wrong response

### ISSUE THREAD

**Issue by sanjeet007** [payu-intrepos/Android-SDK-Sample-App#64]
{
"status": 0,
"message": "payment status for :404211522",
"result": {
"postBackParamId": 301119364,
"mihpayid": "12202000743",
"paymentId": 404211522,
"mode": "UPI",
"status": "success",
"unmappedstatus": "captured",
"key": "DOC5Aa40",
"txnid": "TXNID1612265893694",
"amount": "1.00",
"additionalCharges": "",
"addedon": "2021-02-02 17:30:26",
"createdOn": 1612267396000,
"productinfo": "Watc Assist",
"firstname": "San Kumar",
"lastname": "",
"address1": "",
"address2": "",
"city": "",
"state": "",
"country": "",
"zipcode": "",
"email": "san@gmail.com",
"phone": "8004306568",
"udf1": "",
"udf2": "",
"udf3": "",
"udf4": "",
"udf5": "",
"udf6": "",
"udf7": "",
"udf8": "",
"udf9": "",
"udf10": "",
"hash": "7c15cad6fc7ae9e283e93e004afdfddfeac624601049471a5eee26616d9e3352a2b18e2418d4c3f7afe9213fbf3f04d423e1abe3b25acca25628rgfert829e34",
"field1": "superbsaddu49@okaxis",
"field2": "103317707818",
"field3": "superbsanju49@okaxis",
"field4": "SANJEEV KUMAR",
"field5": "AXI3a935e4c57774775b4505827c00acfbf",
"field6": "",
"field7": "APPROVED OR COMPLETED SUCCESSFULLY|00",
"field8": "",
"field9": "Success|Completed Using Callback",
"bank_ref_num": "103317707818",
"bankcode": "UPI",
"error": "E000",
"error_Message": "No Error",
"cardToken": "",
"offer_key": "",
"offer_type": "",
"offer_availed": "",
"pg_ref_no": "",
"offer_failure_reason": "",
"name_on_card": "",
"cardnum": "",
"cardhash": "",
"card_type": "",
"card_merchant_param": null,
"version": "",
"postUrl": "https://www.payumoney.com/mobileapp/payumoney/success.php",
"calledStatus": false,
"additional_param": "",
"amount_split": "{\"PAYU\":\"1.00\"}",
"discount": "",
"net_amount_debit": "1",
"fetchAPI": null,
"paisa_mecode": "",
"meCode": "{\"merchId\":\"PAYUPAPROD004281\",\"merchChanId\":\"PAYUPAPRODAPP004281\",\"sId\":\"2\",\"merchantVpa\":\"payumoney.payu@axisbank\",\"intentMerchId\":\"PAYUPROD005\",\"int",
"payuMoneyId": "404211522",
"encryptedPaymentId": null,
"id": null,
"surl": null,
"furl": null,
"baseUrl": null,
"retryCount": 0,
"merchantid": null,
"payment_source": null,
"isConsentPayment": 0,
"giftCardIssued": true,
"pg_TYPE": "AXISU",
"s2SPbpFlag": false
},
"errorCode": null,
"responseCode": null
}

{\"merchId\":\"PAYUPAPROD004281\",\"merchChanId\":\"PAYUPAPRODAPP004281\",\"sId\":\"2\",\"merchantVpa\":\"payumoney.payu@axisbank\",\"intentMerchId\":\"PAYUPROD005\",\"int",

this is incomplete json string and why this is wrong and why some are in stringified 

and tell me it is wronng response or correct

**Comment by himgupta229** [comment]
Please drop a mail to mobile.integration@payu.in.
