### ISSUE TITLE
About payu,is there any .jar supporting this import

### ISSUE THREAD

**Issue by tindumanilal** [payu-intrepos/Android-SDK-Sample-App#7]
import com.payu.india.Extras.PayUSdkDetails;
import com.payu.india.Model.PaymentParams;
import com.payu.india.Model.PayuConfig;
import com.payu.india.Model.PayuHashes;
import com.payu.india.Payu.PayuConstants;
import com.payu.india.Model.PostData;
import com.payu.india.Payu.PayuErrors;
import com.payu.india.Extras.PayUChecksum;

**Comment by Franklin2412** [comment]
Yeah, it is on testing phase, we will update in one or two days.

**Comment by Franklin2412** [comment]
Hey, we have updated payusdk jar. please check https://github.com/payu-intrepos/Android-SDK
